AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: RulePlay - RulesService (Micronaut Lambda HTTP API v2)

Globals:
  Function:
    Runtime: java21
    Architectures: [ arm64 ]
    MemorySize: 512
    Timeout: 15
    Tracing: Active

Parameters:
  StageName:
    Type: String
    Default: dev

Resources:
  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      CorsConfiguration:
        AllowOrigins: ['*']
        AllowMethods: ['GET','OPTIONS']
        AllowHeaders: ['Content-Type','Authorization']

  RulesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java21
      Handler: app.rules.Function
      CodeUri: GetRulesFunction/
      Environment:
        Variables:
          RULES_TABLE: RulePlay-Rules-dev
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:GetItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/RulePlay-Rules-dev
      Events:
        Root:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Path: /
            Method: ANY
        Any:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Value: !Sub https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${StageName}